# Generated by Django 3.2 on 2021-05-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price'], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
